-- 0003_add_timeline_events.sql
--
-- SOC-IQ Phase A4-P2-P3, Part 1/6 -- Investigation Timeline
-- foundation (docs/architecture/20-investigation-timeline-architecture.md).
--
-- Adds a single new, additive table: `timeline_events`. Does not
-- alter, rename, or drop any existing table or column (including
-- `investigations`, most recently changed by 0002). No existing
-- data is rewritten.
--
-- Design notes:
--
-- * `event_id` is the TEXT uuid4-hex primary key generated by
--   app.timeline.domain.TimelineEvent (Python-side identity, same
--   strategy as app.application.events.Event) -- not an
--   AUTOINCREMENT integer, because event identity must be stable
--   and assignable before the row is ever inserted.
--
-- * `investigation_id` is a foreign key to `investigations.id`
--   (the *existing* investigation identity -- see
--   app/database/models.py, app/database/migrations/0001_initial.sql).
--   `ON DELETE CASCADE`: this project already performs hard deletes
--   of investigations (InvestigationRepository.delete), which
--   already destroys that investigation's iocs/threat_intelligence/
--   risk data outright. A timeline_events row for a deleted
--   investigation records history about evidence that no longer
--   exists, so it is deleted along with its parent rather than left
--   as an orphan FK violation or kept as a dangling reference to
--   nothing. This is a per-investigation retention choice, not a
--   database-wide default -- `PRAGMA foreign_keys` is already ON
--   for every connection (app/database/connection.py) -- this
--   migration does not change that.
--
-- * `event_type` is CHECK-constrained to the exact controlled
--   vocabulary in app.timeline.domain.TimelineEventType, so a bug
--   that bypasses the Python-side enum validation cannot silently
--   write an arbitrary string into permanent history. Extending
--   the vocabulary requires a new migration that rewrites this
--   CHECK clause, by design -- it is meant to be deliberately
--   annoying to add a new event type.
--
-- * `timestamp` is stored as TEXT (ISO-8601, UTC, e.g.
--   "2026-08-20T10:15:32.123456+00:00"), matching
--   `investigations.analyzed_at`'s existing storage convention
--   (see 0001_initial.sql / app/database/repository.py, which
--   stores `datetime.isoformat()` and reads it back with
--   `datetime.fromisoformat()`). No second timestamp representation
--   is introduced.
--
-- * `metadata` is stored as TEXT (JSON), matching the existing
--   `investigations.iocs` / `investigations.threat_intelligence`
--   convention of storing JSON-serialized dicts as TEXT (SQLite has
--   no native JSON column type). NULL means "no metadata", distinct
--   from the empty-object case.
--
-- * No `UNIQUE` constraint on (investigation_id, event_type):
--   per the Part 1 brief, duplicate/repeated legitimate events
--   (e.g. two ANALYSIS_STARTED events for two separate analysis
--   runs of the same investigation) are allowed. `event_id`
--   already distinguishes every row.
--
-- * Ordering: the dominant query is "timeline events for
--   investigation X, oldest to newest, deterministically". A
--   timestamp column alone is not sufficient as a *sole* ordering
--   key, since two events can share the same wall-clock instant
--   (down to the stored microsecond resolution). This table
--   intentionally has an ordinary SQLite `rowid` (it is not
--   declared `WITHOUT ROWID`), which is a strictly increasing
--   insertion-order integer -- the repository orders by
--   `(timestamp, rowid)`, giving stable tie-breaking without a
--   redundant hand-maintained sequence column.

CREATE TABLE IF NOT EXISTS timeline_events (
    event_id TEXT PRIMARY KEY,
    investigation_id INTEGER NOT NULL,
    event_type TEXT NOT NULL CHECK (
        event_type IN (
            'investigation.created',
            'report.imported',
            'analysis.started',
            'analysis.completed',
            'ioc_extraction.completed',
            'ti.enrichment.completed',
            'risk.calculated',
            'correlation.completed',
            'report.exported'
        )
    ),
    timestamp TEXT NOT NULL,
    source TEXT NOT NULL,
    summary TEXT NOT NULL,
    metadata TEXT NULL,
    FOREIGN KEY (investigation_id)
        REFERENCES investigations (id)
        ON DELETE CASCADE
);

-- Serves the dominant query: "timeline for investigation X, ordered
-- by timestamp". investigation_id is listed first since every query
-- filters by it -- timestamp second since every query orders by it.
CREATE INDEX IF NOT EXISTS idx_timeline_events_investigation_timestamp
    ON timeline_events (investigation_id, timestamp);
